/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INFTContract, INFTContractInterface } from "../INFTContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INFTContract__factory {
  static readonly abi = _abi;
  static createInterface(): INFTContractInterface {
    return new utils.Interface(_abi) as INFTContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTContract {
    return new Contract(address, _abi, signerOrProvider) as INFTContract;
  }
}
